
<MainScreen@BoxLayout>:
    orientation: "vertical"
    spacing: 10
    padding: 10

    BoxLayout:
        orientation: "vertical"
        size_hint_y: 0.025

    Image:
        source: root.image_path

    Popup:
        id: file_popup
        title: "Seleccionar Imagen"
        size_hint: 1.2,1.2
        auto_dismiss: False

        BoxLayout:
            orientation: 'vertical'
            padding: 10

            FileChooserIconView:
                id: filechooser
                path: root.initial_path
                filters: ['*.png', '*.jpg', '*.jpeg', '*.bmp']
                on_selection: root.selecciona_archivo(self.selection)

            BoxLayout:
                size_hint_y: 0.1

                Button:
                    text: "Cargar Imagen"
                    on_press:
                        root.abrir_archivo(filechooser.selection)
                        file_popup.dismiss()
                    size_hint_x: 0.3
                Button:
                    text: "Reiniciar imagen"
                    on_press: root.image_path = ''
                    size_hint_x: 0.5

MainScreen:
